languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Alex Oh"

[params]
  dateFormat = "2 January 2006"
  description = "Personal website of Alex Oh"

[params.author]
  name = "Alexander Oh"
  image = "img/profile.jpeg"
  headline = "Aspiring Data Scientist"
  bio = "Aspiring Data Scientist"
  links = [
    { github = "https://github.com/alexoh2bd/" },
    { linkedin = "https://www.linkedin.com/in/alexoh2024/" },
    { kaggle = "https://www.kaggle.com/alexooh" },
  ]